In [1]:
#Naive_Gauss Pseudocode copied
import numpy as np
import sys

In [2]:
#Naive_Gauss Pseudocode For Python
def Naive_Gauss(A, B):
    n = len(B)
    # Elimination phase
    for k in range(0, n-1):
        for i in range(k+1, n):
            if A[i,k] != 0.0:
                lam = A[i,k]/A[k,k]
                A[i,k+1:n] = A[i,k+1:n] - lam*A[k,k+1:n]
                B[i] = B[i] - lam*B[k]
    # Back substitution
    for k in range(n-1, -1, -1):
        B[k] = (B[k] - np.dot(A[k,k+1:n],B[k+1:n]))/A[k,k]
    return B

In [3]:
A = np.array([[2, 1, 1],
              [-1, 1, -1],
              [1, 2, 3]], dtype = float)

B = np.array([2, 3, -10], dtype = float)
X = Naive_Gauss(A, B)
print(X)
#answer [3,1,-5]

[ 3.  1. -5.]


In [4]:
A = np.array([[2, 1, 1, 2],
              [-1, 1, -1, 3],
              [1, 2, 3, -10]], dtype = float)
rows = np.shape(A)[0]
cols = np.shape(A)[1]
print(rows)
print(cols)

3
4


In [9]:
m = 10
#A = np.array(zeros_like)
#B = np.array(zeros_like)
A = np.arange(m*m,dtype=float).reshape(m, m)   #, dtype=np.int32
B = np.arange(10,dtype=float)
print(A)
print(B)
for n in range(4,m):
    for i in range(1,n):
        for j in range(1,n):
            A[i][j] = (i+1)**(j-1)
        B[i] = (((i+1)**n)-1)/i
print("\n",A,"\n",B)
X = Naive_Gauss(A,B)
print("\n",X)

[[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14. 15. 16. 17. 18. 19.]
 [20. 21. 22. 23. 24. 25. 26. 27. 28. 29.]
 [30. 31. 32. 33. 34. 35. 36. 37. 38. 39.]
 [40. 41. 42. 43. 44. 45. 46. 47. 48. 49.]
 [50. 51. 52. 53. 54. 55. 56. 57. 58. 59.]
 [60. 61. 62. 63. 64. 65. 66. 67. 68. 69.]
 [70. 71. 72. 73. 74. 75. 76. 77. 78. 79.]
 [80. 81. 82. 83. 84. 85. 86. 87. 88. 89.]
 [90. 91. 92. 93. 94. 95. 96. 97. 98. 99.]]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]

 [[0.000000e+00 1.000000e+00 2.000000e+00 3.000000e+00 4.000000e+00
  5.000000e+00 6.000000e+00 7.000000e+00 8.000000e+00 9.000000e+00]
 [1.000000e+01 1.000000e+00 2.000000e+00 4.000000e+00 8.000000e+00
  1.600000e+01 3.200000e+01 6.400000e+01 1.280000e+02 1.900000e+01]
 [2.000000e+01 1.000000e+00 3.000000e+00 9.000000e+00 2.700000e+01
  8.100000e+01 2.430000e+02 7.290000e+02 2.187000e+03 2.900000e+01]
 [3.000000e+01 1.000000e+00 4.000000e+00 1.600000e+01 6.400000e+01
  2.560000e+02 1.024000e+03 4.096000e+03 1.638400e+04 3.900000e

C:\Users\ramie\AppData\Local\Temp/ipykernel_19692/1768707043.py:8: RuntimeWarning: divide by zero encountered in double_scalars
  lam = A[i,k]/A[k,k]
C:\Users\ramie\AppData\Local\Temp/ipykernel_19692/1768707043.py:10: RuntimeWarning: invalid value encountered in double_scalars
  B[i] = B[i] - lam*B[k]
C:\Users\ramie\AppData\Local\Temp/ipykernel_19692/1768707043.py:8: RuntimeWarning: invalid value encountered in double_scalars
  lam = A[i,k]/A[k,k]


In [10]:
A = np.array([[1.0, 0, 3],
              [0, 1, -3],
              [3, -3, 0],
              [0, 2, 4]])
B = np.array([0.0, 0, 6, -6])
print(A, "\n")
print(B, "\n")

X = Naive_Gauss(A,B)
print(X,"\n")

[[ 1.  0.  3.]
 [ 0.  1. -3.]
 [ 3. -3.  0.]
 [ 0.  2.  4.]] 

[ 0.  0.  6. -6.] 



IndexError: index 3 is out of bounds for axis 1 with size 3